print("test" == "test")
print(1 == 1 or 2 != 1)
print(True and 1 == 1)
print(False and 0 != 0)
print(True or 1 ==1)
print("test" == "testing")
print(1 != 0 and 2 == 1)
print("test" != "testing")
print("test" == 1)
print(not (True and False))
print(not("testing" == "testing" and "Zobaier" == "cool guy"))
print("chunky" == "bacon" and (not(3 == 4 or 3 == 3)))
